server:
  port: 8080
  servlet:
    context-path: /start



spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/start'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "pbMmaJXWhDerMAIah+6KQeNqW0vnQHURIDVmX2g0kRtE5Ax2YCcvQeL9zoBfRXm3"